### ISSUE TITLE
Errors when use other models

### ISSUE THREAD

**Issue by paulo-coutinho** [TencentARC/GFPGAN#125]
Hi,

I have download all and tested with "GFPGANCleanv1-NoCE-C2.pth" and it worked nice.

But with all other i have problems.

With "GFPGANv1.pth" i got:

<details><summary>CLICK ME</summary>

```
rm -rf results && python inference_gfpgan.py --upscale 2 --test_path inputs/demo --save_root results --model_path experiments/pretrained_models/GFPGANv1.pth --bg_upsampler realesrgan
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/inference_gfpgan.py", line 116, in <module>
    main()
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/inference_gfpgan.py", line 63, in main
    restorer = GFPGANer(
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/gfpgan/utils.py", line 79, in __init__
    self.gfpgan.load_state_dict(loadnet[keyname], strict=True)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GFPGANv1Clean:
	Missing key(s) in state_dict: "conv_body_first.weight", "conv_body_first.bias", "conv_body_down.0.conv1.weight", "conv_body_down.0.conv1.bias", "conv_body_down.0.conv2.weight", "conv_body_down.0.conv2.bias", "conv_body_down.0.skip.weight", "conv_body_down.1.conv1.weight", "conv_body_down.1.conv1.bias", "conv_body_down.1.conv2.weight", "conv_body_down.1.conv2.bias", "conv_body_down.1.skip.weight", "conv_body_down.2.conv1.weight", "conv_body_down.2.conv1.bias", "conv_body_down.2.conv2.weight", "conv_body_down.2.conv2.bias", "conv_body_down.2.skip.weight", "conv_body_down.3.conv1.weight", "conv_body_down.3.conv1.bias", "conv_body_down.3.conv2.weight", "conv_body_down.3.conv2.bias", "conv_body_down.3.skip.weight", "conv_body_down.4.conv1.weight", "conv_body_down.4.conv1.bias", "conv_body_down.4.conv2.weight", "conv_body_down.4.conv2.bias", "conv_body_down.4.skip.weight", "conv_body_down.5.conv1.weight", "conv_body_down.5.conv1.bias", "conv_body_down.5.conv2.weight", "conv_body_down.5.conv2.bias", "conv_body_down.5.skip.weight", "conv_body_down.6.conv1.weight", "conv_body_down.6.conv1.bias", "conv_body_down.6.conv2.weight", "conv_body_down.6.conv2.bias", "conv_body_down.6.skip.weight", "final_conv.weight", "final_conv.bias", "conv_body_up.0.conv1.weight", "conv_body_up.0.conv1.bias", "conv_body_up.0.conv2.bias", "conv_body_up.1.conv1.weight", "conv_body_up.1.conv1.bias", "conv_body_up.1.conv2.bias", "conv_body_up.2.conv1.weight", "conv_body_up.2.conv1.bias", "conv_body_up.2.conv2.bias", "conv_body_up.3.conv1.weight", "conv_body_up.3.conv1.bias", "conv_body_up.3.conv2.bias", "conv_body_up.4.conv1.weight", "conv_body_up.4.conv1.bias", "conv_body_up.4.conv2.bias", "conv_body_up.5.conv1.weight", "conv_body_up.5.conv1.bias", "conv_body_up.5.conv2.bias", "conv_body_up.6.conv1.weight", "conv_body_up.6.conv1.bias", "conv_body_up.6.conv2.bias", "stylegan_decoder.style_mlp.9.weight", "stylegan_decoder.style_mlp.9.bias", "stylegan_decoder.style_mlp.11.weight", "stylegan_decoder.style_mlp.11.bias", "stylegan_decoder.style_mlp.13.weight", "stylegan_decoder.style_mlp.13.bias", "stylegan_decoder.style_mlp.15.weight", "stylegan_decoder.style_mlp.15.bias", "stylegan_decoder.style_conv1.bias", "stylegan_decoder.style_convs.0.bias", "stylegan_decoder.style_convs.1.bias", "stylegan_decoder.style_convs.2.bias", "stylegan_decoder.style_convs.3.bias", "stylegan_decoder.style_convs.4.bias", "stylegan_decoder.style_convs.5.bias", "stylegan_decoder.style_convs.6.bias", "stylegan_decoder.style_convs.7.bias", "stylegan_decoder.style_convs.8.bias", "stylegan_decoder.style_convs.9.bias", "stylegan_decoder.style_convs.10.bias", "stylegan_decoder.style_convs.11.bias", "stylegan_decoder.style_convs.12.bias", "stylegan_decoder.style_convs.13.bias". 
	Unexpected key(s) in state_dict: "conv_body_first.0.weight", "conv_body_first.1.bias", "conv_body_down.0.conv1.0.weight", "conv_body_down.0.conv1.1.bias", "conv_body_down.0.conv2.1.weight", "conv_body_down.0.conv2.2.bias", "conv_body_down.0.skip.1.weight", "conv_body_down.1.conv1.0.weight", "conv_body_down.1.conv1.1.bias", "conv_body_down.1.conv2.1.weight", "conv_body_down.1.conv2.2.bias", "conv_body_down.1.skip.1.weight", "conv_body_down.2.conv1.0.weight", "conv_body_down.2.conv1.1.bias", "conv_body_down.2.conv2.1.weight", "conv_body_down.2.conv2.2.bias", "conv_body_down.2.skip.1.weight", "conv_body_down.3.conv1.0.weight", "conv_body_down.3.conv1.1.bias", "conv_body_down.3.conv2.1.weight", "conv_body_down.3.conv2.2.bias", "conv_body_down.3.skip.1.weight", "conv_body_down.4.conv1.0.weight", "conv_body_down.4.conv1.1.bias", "conv_body_down.4.conv2.1.weight", "conv_body_down.4.conv2.2.bias", "conv_body_down.4.skip.1.weight", "conv_body_down.5.conv1.0.weight", "conv_body_down.5.conv1.1.bias", "conv_body_down.5.conv2.1.weight", "conv_body_down.5.conv2.2.bias", "conv_body_down.5.skip.1.weight", "conv_body_down.6.conv1.0.weight", "conv_body_down.6.conv1.1.bias", "conv_body_down.6.conv2.1.weight", "conv_body_down.6.conv2.2.bias", "conv_body_down.6.skip.1.weight", "final_conv.0.weight", "final_conv.1.bias", "conv_body_up.0.conv1.0.weight", "conv_body_up.0.conv1.1.bias", "conv_body_up.0.conv2.activation.bias", "conv_body_up.1.conv1.0.weight", "conv_body_up.1.conv1.1.bias", "conv_body_up.1.conv2.activation.bias", "conv_body_up.2.conv1.0.weight", "conv_body_up.2.conv1.1.bias", "conv_body_up.2.conv2.activation.bias", "conv_body_up.3.conv1.0.weight", "conv_body_up.3.conv1.1.bias", "conv_body_up.3.conv2.activation.bias", "conv_body_up.4.conv1.0.weight", "conv_body_up.4.conv1.1.bias", "conv_body_up.4.conv2.activation.bias", "conv_body_up.5.conv1.0.weight", "conv_body_up.5.conv1.1.bias", "conv_body_up.5.conv2.activation.bias", "conv_body_up.6.conv1.0.weight", "conv_body_up.6.conv1.1.bias", "conv_body_up.6.conv2.activation.bias", "stylegan_decoder.style_mlp.2.weight", "stylegan_decoder.style_mlp.2.bias", "stylegan_decoder.style_mlp.4.weight", "stylegan_decoder.style_mlp.4.bias", "stylegan_decoder.style_mlp.6.weight", "stylegan_decoder.style_mlp.6.bias", "stylegan_decoder.style_mlp.8.weight", "stylegan_decoder.style_mlp.8.bias", "stylegan_decoder.style_conv1.activate.bias", "stylegan_decoder.style_convs.0.activate.bias", "stylegan_decoder.style_convs.1.activate.bias", "stylegan_decoder.style_convs.2.activate.bias", "stylegan_decoder.style_convs.3.activate.bias", "stylegan_decoder.style_convs.4.activate.bias", "stylegan_decoder.style_convs.5.activate.bias", "stylegan_decoder.style_convs.6.activate.bias", "stylegan_decoder.style_convs.7.activate.bias", "stylegan_decoder.style_convs.8.activate.bias", "stylegan_decoder.style_convs.9.activate.bias", "stylegan_decoder.style_convs.10.activate.bias", "stylegan_decoder.style_convs.11.activate.bias", "stylegan_decoder.style_convs.12.activate.bias", "stylegan_decoder.style_convs.13.activate.bias".
```
</details>

With "GFPGANCleanv1-NoCE-C2_original_net_d.pth" download from google drive i got:

<details><summary>CLICK ME</summary>

```
rm -rf results && python inference_gfpgan.py --upscale 2 --test_path inputs/demo --save_root results --model_path experiments/pretrained_models/GFPGANCleanv1-NoCE-C2_original_net_d.pth
Traceback (most recent call last):
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/inference_gfpgan.py", line 116, in <module>
    main()
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/inference_gfpgan.py", line 63, in main
    restorer = GFPGANer(
  File "/Users/paulo/Developer/workspaces/python/GFPGAN/gfpgan/utils.py", line 79, in __init__
    self.gfpgan.load_state_dict(loadnet[keyname], strict=True)
  File "/usr/local/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for GFPGANv1Clean:
	Missing key(s) in state_dict: "conv_body_first.weight", "conv_body_first.bias", "conv_body_down.0.conv1.weight", "conv_body_down.0.conv1.bias", "conv_body_down.0.conv2.weight", "conv_body_down.0.conv2.bias", "conv_body_down.0.skip.weight", "conv_body_down.1.conv1.weight", "conv_body_down.1.conv1.bias", "conv_body_down.1.conv2.weight", "conv_body_down.1.conv2.bias", "conv_body_down.1.skip.weight", "conv_body_down.2.conv1.weight", "conv_body_down.2.conv1.bias", "conv_body_down.2.conv2.weight", "conv_body_down.2.conv2.bias", "conv_body_down.2.skip.weight", "conv_body_down.3.conv1.weight", "conv_body_down.3.conv1.bias", "conv_body_down.3.conv2.weight", "conv_body_down.3.conv2.bias", "conv_body_down.3.skip.weight", "conv_body_down.4.conv1.weight", "conv_body_down.4.conv1.bias", "conv_body_down.4.conv2.weight", "conv_body_down.4.conv2.bias", "conv_body_down.4.skip.weight", "conv_body_down.5.conv1.weight", "conv_body_down.5.conv1.bias", "conv_body_down.5.conv2.weight", "conv_body_down.5.conv2.bias", "conv_body_down.5.skip.weight", "conv_body_down.6.conv1.weight", "conv_body_down.6.conv1.bias", "conv_body_down.6.conv2.weight", "conv_body_down.6.conv2.bias", "conv_body_down.6.skip.weight", "final_conv.weight", "final_conv.bias", "conv_body_up.0.conv1.weight", "conv_body_up.0.conv1.bias", "conv_body_up.0.conv2.weight", "conv_body_up.0.conv2.bias", "conv_body_up.0.skip.weight", "conv_body_up.1.conv1.weight", "conv_body_up.1.conv1.bias", "conv_body_up.1.conv2.weight", "conv_body_up.1.conv2.bias", "conv_body_up.1.skip.weight", "conv_body_up.2.conv1.weight", "conv_body_up.2.conv1.bias", "conv_body_up.2.conv2.weight", "conv_body_up.2.conv2.bias", "conv_body_up.2.skip.weight", "conv_body_up.3.conv1.weight", "conv_body_up.3.conv1.bias", "conv_body_up.3.conv2.weight", "conv_body_up.3.conv2.bias", "conv_body_up.3.skip.weight", "conv_body_up.4.conv1.weight", "conv_body_up.4.conv1.bias", "conv_body_up.4.conv2.weight", "conv_body_up.4.conv2.bias", "conv_body_up.4.skip.weight", "conv_body_up.5.conv1.weight", "conv_body_up.5.conv1.bias", "conv_body_up.5.conv2.weight", "conv_body_up.5.conv2.bias", "conv_body_up.5.skip.weight", "conv_body_up.6.conv1.weight", "conv_body_up.6.conv1.bias", "conv_body_up.6.conv2.weight", "conv_body_up.6.conv2.bias", "conv_body_up.6.skip.weight", "toRGB.0.weight", "toRGB.0.bias", "toRGB.1.weight", "toRGB.1.bias", "toRGB.2.weight", "toRGB.2.bias", "toRGB.3.weight", "toRGB.3.bias", "toRGB.4.weight", "toRGB.4.bias", "toRGB.5.weight", "toRGB.5.bias", "toRGB.6.weight", "toRGB.6.bias", "final_linear.weight", "final_linear.bias", "stylegan_decoder.style_mlp.1.weight", "stylegan_decoder.style_mlp.1.bias", "stylegan_decoder.style_mlp.3.weight", "stylegan_decoder.style_mlp.3.bias", "stylegan_decoder.style_mlp.5.weight", "stylegan_decoder.style_mlp.5.bias", "stylegan_decoder.style_mlp.7.weight", "stylegan_decoder.style_mlp.7.bias", "stylegan_decoder.style_mlp.9.weight", "stylegan_decoder.style_mlp.9.bias", "stylegan_decoder.style_mlp.11.weight", "stylegan_decoder.style_mlp.11.bias", "stylegan_decoder.style_mlp.13.weight", "stylegan_decoder.style_mlp.13.bias", "stylegan_decoder.style_mlp.15.weight", "stylegan_decoder.style_mlp.15.bias", "stylegan_decoder.constant_input.weight", "stylegan_decoder.style_conv1.weight", "stylegan_decoder.style_conv1.bias", "stylegan_decoder.style_conv1.modulated_conv.weight", "stylegan_decoder.style_conv1.modulated_conv.modulation.weight", "stylegan_decoder.style_conv1.modulated_conv.modulation.bias", "stylegan_decoder.to_rgb1.bias", "stylegan_decoder.to_rgb1.modulated_conv.weight", "stylegan_decoder.to_rgb1.modulated_conv.modulation.weight", "stylegan_decoder.to_rgb1.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.0.weight", "stylegan_decoder.style_convs.0.bias", "stylegan_decoder.style_convs.0.modulated_conv.weight", "stylegan_decoder.style_convs.0.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.0.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.1.weight", "stylegan_decoder.style_convs.1.bias", "stylegan_decoder.style_convs.1.modulated_conv.weight", "stylegan_decoder.style_convs.1.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.1.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.2.weight", "stylegan_decoder.style_convs.2.bias", "stylegan_decoder.style_convs.2.modulated_conv.weight", "stylegan_decoder.style_convs.2.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.2.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.3.weight", "stylegan_decoder.style_convs.3.bias", "stylegan_decoder.style_convs.3.modulated_conv.weight", "stylegan_decoder.style_convs.3.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.3.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.4.weight", "stylegan_decoder.style_convs.4.bias", "stylegan_decoder.style_convs.4.modulated_conv.weight", "stylegan_decoder.style_convs.4.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.4.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.5.weight", "stylegan_decoder.style_convs.5.bias", "stylegan_decoder.style_convs.5.modulated_conv.weight", "stylegan_decoder.style_convs.5.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.5.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.6.weight", "stylegan_decoder.style_convs.6.bias", "stylegan_decoder.style_convs.6.modulated_conv.weight", "stylegan_decoder.style_convs.6.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.6.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.7.weight", "stylegan_decoder.style_convs.7.bias", "stylegan_decoder.style_convs.7.modulated_conv.weight", "stylegan_decoder.style_convs.7.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.7.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.8.weight", "stylegan_decoder.style_convs.8.bias", "stylegan_decoder.style_convs.8.modulated_conv.weight", "stylegan_decoder.style_convs.8.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.8.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.9.weight", "stylegan_decoder.style_convs.9.bias", "stylegan_decoder.style_convs.9.modulated_conv.weight", "stylegan_decoder.style_convs.9.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.9.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.10.weight", "stylegan_decoder.style_convs.10.bias", "stylegan_decoder.style_convs.10.modulated_conv.weight", "stylegan_decoder.style_convs.10.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.10.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.11.weight", "stylegan_decoder.style_convs.11.bias", "stylegan_decoder.style_convs.11.modulated_conv.weight", "stylegan_decoder.style_convs.11.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.11.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.12.weight", "stylegan_decoder.style_convs.12.bias", "stylegan_decoder.style_convs.12.modulated_conv.weight", "stylegan_decoder.style_convs.12.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.12.modulated_conv.modulation.bias", "stylegan_decoder.style_convs.13.weight", "stylegan_decoder.style_convs.13.bias", "stylegan_decoder.style_convs.13.modulated_conv.weight", "stylegan_decoder.style_convs.13.modulated_conv.modulation.weight", "stylegan_decoder.style_convs.13.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.0.bias", "stylegan_decoder.to_rgbs.0.modulated_conv.weight", "stylegan_decoder.to_rgbs.0.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.0.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.1.bias", "stylegan_decoder.to_rgbs.1.modulated_conv.weight", "stylegan_decoder.to_rgbs.1.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.1.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.2.bias", "stylegan_decoder.to_rgbs.2.modulated_conv.weight", "stylegan_decoder.to_rgbs.2.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.2.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.3.bias", "stylegan_decoder.to_rgbs.3.modulated_conv.weight", "stylegan_decoder.to_rgbs.3.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.3.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.4.bias", "stylegan_decoder.to_rgbs.4.modulated_conv.weight", "stylegan_decoder.to_rgbs.4.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.4.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.5.bias", "stylegan_decoder.to_rgbs.5.modulated_conv.weight", "stylegan_decoder.to_rgbs.5.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.5.modulated_conv.modulation.bias", "stylegan_decoder.to_rgbs.6.bias", "stylegan_decoder.to_rgbs.6.modulated_conv.weight", "stylegan_decoder.to_rgbs.6.modulated_conv.modulation.weight", "stylegan_decoder.to_rgbs.6.modulated_conv.modulation.bias", "stylegan_decoder.noises.noise0", "stylegan_decoder.noises.noise1", "stylegan_decoder.noises.noise2", "stylegan_decoder.noises.noise3", "stylegan_decoder.noises.noise4", "stylegan_decoder.noises.noise5", "stylegan_decoder.noises.noise6", "stylegan_decoder.noises.noise7", "stylegan_decoder.noises.noise8", "stylegan_decoder.noises.noise9", "stylegan_decoder.noises.noise10", "stylegan_decoder.noises.noise11", "stylegan_decoder.noises.noise12", "stylegan_decoder.noises.noise13", "stylegan_decoder.noises.noise14", "condition_scale.0.0.weight", "condition_scale.0.0.bias", "condition_scale.0.2.weight", "condition_scale.0.2.bias", "condition_scale.1.0.weight", "condition_scale.1.0.bias", "condition_scale.1.2.weight", "condition_scale.1.2.bias", "condition_scale.2.0.weight", "condition_scale.2.0.bias", "condition_scale.2.2.weight", "condition_scale.2.2.bias", "condition_scale.3.0.weight", "condition_scale.3.0.bias", "condition_scale.3.2.weight", "condition_scale.3.2.bias", "condition_scale.4.0.weight", "condition_scale.4.0.bias", "condition_scale.4.2.weight", "condition_scale.4.2.bias", "condition_scale.5.0.weight", "condition_scale.5.0.bias", "condition_scale.5.2.weight", "condition_scale.5.2.bias", "condition_scale.6.0.weight", "condition_scale.6.0.bias", "condition_scale.6.2.weight", "condition_scale.6.2.bias", "condition_shift.0.0.weight", "condition_shift.0.0.bias", "condition_shift.0.2.weight", "condition_shift.0.2.bias", "condition_shift.1.0.weight", "condition_shift.1.0.bias", "condition_shift.1.2.weight", "condition_shift.1.2.bias", "condition_shift.2.0.weight", "condition_shift.2.0.bias", "condition_shift.2.2.weight", "condition_shift.2.2.bias", "condition_shift.3.0.weight", "condition_shift.3.0.bias", "condition_shift.3.2.weight", "condition_shift.3.2.bias", "condition_shift.4.0.weight", "condition_shift.4.0.bias", "condition_shift.4.2.weight", "condition_shift.4.2.bias", "condition_shift.5.0.weight", "condition_shift.5.0.bias", "condition_shift.5.2.weight", "condition_shift.5.2.bias", "condition_shift.6.0.weight", "condition_shift.6.0.bias", "condition_shift.6.2.weight", "condition_shift.6.2.bias". 
	Unexpected key(s) in state_dict: "conv_body.0.0.weight", "conv_body.0.1.bias", "conv_body.1.conv1.0.weight", "conv_body.1.conv1.1.bias", "conv_body.1.conv2.1.weight", "conv_body.1.conv2.2.bias", "conv_body.1.skip.1.weight", "conv_body.2.conv1.0.weight", "conv_body.2.conv1.1.bias", "conv_body.2.conv2.1.weight", "conv_body.2.conv2.2.bias", "conv_body.2.skip.1.weight", "conv_body.3.conv1.0.weight", "conv_body.3.conv1.1.bias", "conv_body.3.conv2.1.weight", "conv_body.3.conv2.2.bias", "conv_body.3.skip.1.weight", "conv_body.4.conv1.0.weight", "conv_body.4.conv1.1.bias", "conv_body.4.conv2.1.weight", "conv_body.4.conv2.2.bias", "conv_body.4.skip.1.weight", "conv_body.5.conv1.0.weight", "conv_body.5.conv1.1.bias", "conv_body.5.conv2.1.weight", "conv_body.5.conv2.2.bias", "conv_body.5.skip.1.weight", "conv_body.6.conv1.0.weight", "conv_body.6.conv1.1.bias", "conv_body.6.conv2.1.weight", "conv_body.6.conv2.2.bias", "conv_body.6.skip.1.weight", "conv_body.7.conv1.0.weight", "conv_body.7.conv1.1.bias", "conv_body.7.conv2.1.weight", "conv_body.7.conv2.2.bias", "conv_body.7.skip.1.weight", "final_conv.0.weight", "final_conv.1.bias", "final_linear.0.weight", "final_linear.0.bias", "final_linear.1.weight", "final_linear.1.bias". 
```
</details>

1 - What im doing wrong?
2 - How to colorize a grayscale image?

**Comment by Nadavc220** [comment]
Hi mate,
Have a look at the PaperModel.md file.
