### ISSUE TITLE
WIN11安装完所需条件后，提示错误不知道是什么原因

### ISSUE THREAD

**Issue by alimalls** [TencentARC/GFPGAN#166]
WIN11安装完所需条件后，提示错误不知道是什么原因 ，显卡GTX1060

F:\GFPGAN-1.3.2>python inference_gfpgan.py -i inputs/whole_imgs -o results -v 1.3 -s 2
inference_gfpgan.py:62: UserWarning: The unoptimized RealESRGAN is slow on CPU. We do not use it. If you really want to use it, please modify the corresponding codes.
  warnings.warn('The unoptimized RealESRGAN is slow on CPU. We do not use it. '
Traceback (most recent call last):
  File "inference_gfpgan.py", line 155, in <module>
    main()
  File "inference_gfpgan.py", line 108, in main
    bg_upsampler=bg_upsampler)
  File "F:\GFPGAN-1.3.2\gfpgan\utils.py", line 82, in __init__
    device=self.device)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\facexlib\utils\face_restoration_helper.py", line 95, in __init__
    self.face_det = init_detection_model(det_model, half=False, device=device)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\facexlib\detection\__init__.py", line 20, in init_detection_model
    load_net = torch.load(model_path, map_location=lambda storage, loc: storage)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python37\lib\site-packages\torch\serialization.py", line 794, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: unexpected EOF, expected 586079 more bytes. The file might be corrupted.

**Comment by FangmingZhou** [comment]
可以用colab玩

**Comment by shishuifubing** [comment]
可能是wget 模型时不完全，建议手动下载后直接上传至路径
