### ISSUE TITLE
error

### ISSUE THREAD

**Issue by wsysl1989** [TencentARC/GFPGAN#168]
今天下载的，用的v1.3模型，报错，TypeError: get_face_landmarks_5() got an unexpected keyword argument 'eye_dist_threshold'。
之前的版本没问题。

**Comment by wsysl1989** [comment]
Traceback (most recent call last):
  File "D:\python学习\GFPGAN-master\GFPGAN-master\inference_gfpgan.py", line 155, in <module>
    main()
  File "D:\python学习\GFPGAN-master\GFPGAN-master\inference_gfpgan.py", line 119, in main
    cropped_faces, restored_faces, restored_img = restorer.enhance(
  File "D:\Python\lib\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\python学习\GFPGAN-master\GFPGAN-master\gfpgan\utils.py", line 106, in enhance
    self.face_helper.get_face_landmarks_5(only_center_face=only_center_face, eye_dist_threshold=5)
TypeError: get_face_landmarks_5() got an unexpected keyword argument 'eye_dist_threshold'
