### ISSUE TITLE
ImportError: No module named 'deform_conv'

### ISSUE THREAD

**Issue by EndeCC0** [TencentARC/GFPGAN#21]
I run Quick Inference after I finish the installation:
"python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/cropped_faces --aligned". 
Then I encountered the following error:

`(GFPGAN) D:\Profession\Git\GFPGAN>python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/cropped_faces --aligned
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Traceback (most recent call last):
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' (D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 10, in <module>
    from archs.gfpganv1_arch import GFPGANv1
  File "D:\Profession\Git\GFPGAN\archs\__init__.py", line 4, in <module>
    from basicsr.utils import scandir
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\edsr_arch.py", line 4, in <module>
    from basicsr.archs.arch_util import ResidualBlockNoBN, Upsample, make_layer
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\arch_util.py", line 8, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 22, in <module>
    os.path.join(module_path, 'src', 'deform_conv_cuda_kernel.cu'),
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 983, in load
    keep_intermediates=keep_intermediates)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1199, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1546, in _import_module_from_library
    file, path, description = imp.find_module(module_name, [path])
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'deform_conv'`

I found that someone had the same problem as me, but it didn’t solve it.
Is there a solution to this ERROR？Thanks for the ANY HELP~

**Comment by EndeCC0** [comment]
SO... Can this program really run on win10? (confused)

**Comment by EndeCC0** [comment]
One more thing... I have added env variable BASICSR_EXT=True and BASICSR_JIT=True.

**Comment by woctezuma** [comment]
Do you have a GPU?

**Comment by EndeCC0** [comment]
> Do you have a GPU?

Of course, RTX2080Ti.
But I need to install gcc? I see that BasicSR seems to need this.

**Comment by woctezuma** [comment]
https://github.com/xinntao/BasicSR/issues/279, https://github.com/xinntao/BasicSR/issues/280, https://github.com/xinntao/BasicSR/issues/392, https://github.com/xinntao/BasicSR/issues/410, https://github.com/xinntao/BasicSR/issues/416.

**Comment by EndeCC0** [comment]
OK! I will watch these and try to resolve this error. Thank you for your help anyway.

**Comment by EndeCC0** [comment]
After unremitting efforts, I am getting closer and closer to their error... (i don't know whether to laugh or cry.)
Now, I encountered the error that cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' 
The following is the complete error:

> (GFPGAN) D:\Profession\Git\GFPGAN>python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/cropped_faces --aligned
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。
用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]
----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Traceback (most recent call last):
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' (D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 10, in <module>
    from archs.gfpganv1_arch import GFPGANv1
  File "D:\Profession\Git\GFPGAN\archs\__init__.py", line 4, in <module>
    from basicsr.utils import scandir
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\edsr_arch.py", line 4, in <module>
    from basicsr.archs.arch_util import ResidualBlockNoBN, Upsample, make_layer
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\arch_util.py", line 8, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 22, in <module>
    os.path.join(module_path, 'src', 'deform_conv_cuda_kernel.cu'),
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1095, in load
    keep_intermediates=keep_intermediates)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1321, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1704, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed: 找不到指定的模块。

I saw Xintao said that we should run "python setup.py develop" before import it.
But I have used "pip install basicsr" with BASICSR_EXT=True and BASICSR_JIT=True, And I have gcc 8.1 now. Doesn't it work?
If I want to do same things like he said. I download BasicSR and run "python setup.py develop"... Is it related to GFPGAN?
Please treat me as a fool and tell me how to do it, like "one, two, three, four steps". Grateful for ANY HELP.

**Comment by xinntao** [comment]
@EndeCC0 I have not tested on Win10.

Maybe you could try the JIT
1. Uninstall all basicsr and remove cloned basicsr folder.
2.  Git clone basicsr, and go to the basicsr folder, run `BASICSR_EXT=False python setup.py develop`
3. Go to the GFPGAN folder, try to run `BASICSR_JIT=True python xxxx (the cmd)`, and to see what error it raise~

**Comment by xinntao** [comment]
@EndeCC0 I have not tested on Win10.

Maybe you could try the JIT.
1. Uninstall all basicsr and remove cloned basicsr folder.
2.  Git clone basicsr, and go to the basicsr folder, run `BASICSR_EXT=False python setup.py develop`
3. Go to the GFPGAN folder, try to run `BASICSR_JIT=True python xxxx (the cmd)`, and to see what error it raise~

**Comment by EndeCC0** [comment]
OK, I will try.

**Comment by EndeCC0** [comment]
When the previous BASICSR remains in the envs, run "python setup.py develop" witn  ASICSR_EXT=False. The following error raised. 

<details>
<summary>python setup.py develop</summary>

```java
import((GFPGAN) D:\Profession\Git\BasicSR>python setup.py develop
running develop
running egg_info
creating basicsr.egg-info
writing basicsr.egg-info\PKG-INFO
writing dependency_links to basicsr.egg-info\dependency_links.txt
writing requirements to basicsr.egg-info\requires.txt
writing top-level names to basicsr.egg-info\top_level.txt
writing manifest file 'basicsr.egg-info\SOURCES.txt'
reading manifest file 'basicsr.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'basicsr.egg-info\SOURCES.txt'
running build_ext
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
building 'basicsr.ops.dcn.deform_conv_ext' extension
creating D:\Profession\Git\BasicSR\build
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn
creating D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Emitting ninja build file D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
1.10.2
creating D:\Profession\Git\BasicSR\build\lib.win-amd64-3.7
creating D:\Profession\Git\BasicSR\build\lib.win-amd64-3.7\basicsr
creating D:\Profession\Git\BasicSR\build\lib.win-amd64-3.7\basicsr\ops
creating D:\Profession\Git\BasicSR\build\lib.win-amd64-3.7\basicsr\ops\dcn
D:\Profession\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\bin\HostX86\x64\link.exe /nologo /INCREMENTAL:NO /LTCG /DLL /MANIFEST:EMBED,ID=2 /MANIFESTUAC:NO /LIBPATH:D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\lib "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\lib/x64" /LIBPATH:D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\libs /LIBPATH:D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\PCbuild\amd64 "/LIBPATH:D:\Profession\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\ATLMFC\lib\x64" "/LIBPATH:D:\Profession\Program Files\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29910\lib\x64" "/LIBPATH:C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\ucrt\x64" "/LIBPATH:D:\Windows Kits\10\lib\10.0.19041.0\um\x64" "/LIBPATH:D:\Profession\Program Files\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86" "/LIBPATH:D:\Windows Kits\10\Lib\10.0.17763.0\ucrt\x86" c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda.lib /EXPORT:PyInit_deform_conv_ext D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src/deform_conv_ext.obj D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src/deform_conv_cuda.obj D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src/deform_conv_cuda_kernel.obj /OUT:build\lib.win-amd64-3.7\basicsr\ops\dcn\deform_conv_ext.cp37-win_amd64.pyd /IMPLIB:D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src\deform_conv_ext.cp37-win_amd64.lib
LINK : fatal error LNK1181: 无法打开输入文件“D:\Profession\Git\BasicSR\build\temp.win-amd64-3.7\Release\basicsr\ops\dcn\src\deform_conv_ext.obj”
error: command 'D:\\Profession\\Program Files\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.28.29910\\bin\\HostX86\\x64\\link.exe' failed with exit status 1181)
```
</details>



The following error raised when running commands in GPFGAN with BASICSR_JIT=True. 

<details>
<summary> GPFGAN</summary>

```java
import((GFPGAN) D:\Profession\Git\GFPGAN>python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/cropped_faces --aligned
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Traceback (most recent call last):
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' (D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 10, in <module>
    from archs.gfpganv1_arch import GFPGANv1
  File "D:\Profession\Git\GFPGAN\archs\__init__.py", line 4, in <module>
    from basicsr.utils import scandir
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\edsr_arch.py", line 4, in <module>
    from basicsr.archs.arch_util import ResidualBlockNoBN, Upsample, make_layer
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\arch_util.py", line 8, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 22, in <module>
    os.path.join(module_path, 'src', 'deform_conv_cuda_kernel.cu'),
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1095, in load
    keep_intermediates=keep_intermediates)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1321, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1704, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed: 找不到指定的模块。)
```
</details>



After reinstalling BASICSR in the envs, run the code. The following error raised. 

<details>
<summary>python setup.py develop</summary>

```java
import((GFPGAN) D:\Profession\Git\BasicSR>python setup.py develop
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Traceback (most recent call last):
  File "D:\Profession\Git\BasicSR\basicsr\ops\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' (D:\Profession\Git\BasicSR\basicsr\ops\dcn\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 50, in get_hash
    from basicsr.version import __version__
  File "D:\Profession\Git\BasicSR\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Profession\Git\BasicSR\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\Git\BasicSR\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Profession\Git\BasicSR\basicsr\archs\edsr_arch.py", line 4, in <module>
    from basicsr.archs.arch_util import ResidualBlockNoBN, Upsample, make_layer
  File "D:\Profession\Git\BasicSR\basicsr\archs\arch_util.py", line 8, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Profession\Git\BasicSR\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Profession\Git\BasicSR\basicsr\ops\dcn\deform_conv.py", line 22, in <module>
    os.path.join(module_path, 'src', 'deform_conv_cuda_kernel.cu'),
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1095, in load
    keep_intermediates=keep_intermediates)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1321, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1704, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed: 找不到指定的模块。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 139, in <module>
    write_version_py()
  File "setup.py", line 67, in write_version_py
    sha = get_hash()
  File "setup.py", line 53, in get_hash
    raise ImportError('Unable to get git version')
ImportError: Unable to get git version)
```
</details>

Same error  raised when running commands in GPFGAN.

<details>
<summary>GPFGAN</summary>

```java
import((GFPGAN) D:\Profession\Git\GFPGAN>python inference_gfpgan_full.py --model_path experiments/pretrained_models/GFPGANv1.pth --test_path inputs/cropped_faces --aligned
----compiler_info:  用于 x86 的 Microsoft (R) C/C++ 优化编译器 19.16.27045 版
版权所有(C) Microsoft Corporation。保留所有权利。

用法: cl [ 选项... ] 文件名... [ /link 链接选项... ]

----match:  <re.Match object; span=(35, 46), match='19.16.27045'>
Traceback (most recent call last):
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 10, in <module>
    from . import deform_conv_ext
ImportError: cannot import name 'deform_conv_ext' from 'basicsr.ops.dcn' (D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference_gfpgan_full.py", line 10, in <module>
    from archs.gfpganv1_arch import GFPGANv1
  File "D:\Profession\Git\GFPGAN\archs\__init__.py", line 4, in <module>
    from basicsr.utils import scandir
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\edsr_arch.py", line 4, in <module>
    from basicsr.archs.arch_util import ResidualBlockNoBN, Upsample, make_layer
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\archs\arch_util.py", line 8, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 22, in <module>
    os.path.join(module_path, 'src', 'deform_conv_cuda_kernel.cu'),
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1095, in load
    keep_intermediates=keep_intermediates)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1321, in _jit_compile
    return _import_module_from_library(name, build_directory, is_python_module)
  File "D:\Profession\ProgramData\Anaconda3\envs\GFPGAN\lib\site-packages\torch\utils\cpp_extension.py", line 1704, in _import_module_from_library
    module = importlib.util.module_from_spec(spec)
ImportError: DLL load failed: 找不到指定的模块。)
```
</details>

I'm sorry to bother you with so many errors, the errors in GPFGAN are still the same as in the past.

**Comment by EndeCC0** [comment]
Very strange, in order to solve the error of not finding cl, I installed vs2017 and configured it in the system environment. But the error shows vs2019.

**Comment by xinntao** [comment]
The basicsr should not compile the dcn when you set the BASICSR_EXT=False

![image](https://user-images.githubusercontent.com/17445847/126036173-0ce36ad7-b765-44f9-8301-690987cbf008.png)


It may be because the different usage of detecting env variables.
Please try to modify the setup.py file in the BasicSR:
![image](https://user-images.githubusercontent.com/17445847/126036215-5f15e124-0dd8-43f4-8c49-13bcd676a086.png)


Then, run `python setup.py develop`

**Comment by woctezuma** [comment]
>
>
> And I have gcc 8.1 now. Doesn't it work?

Maybe helpful: https://github.com/xinntao/BasicSR/issues/279

**Comment by EndeCC0** [comment]
Thanks for your answers, I will continue to try. It really doesn't work, I can learn to use linux, there is too much to learn. (laugh)

**Comment by ntquyen11** [comment]
@xinntao  when I run **python -m torch.distributed.launch --nproc_per_node=2 --master_port=22021 gfpgan/train.py -opt options/train_gfpgan_v1.yml --launcher pytorch**, I have error **NameError: name 'fused_act_ext' is not defined** so I add  **BASICSR_JIT=True** on the terminal. However, the other error that occurs is same the above one (deform_conv). May you help me??

**Comment by xinntao** [comment]
@ntquyen11 What env do you use?
and you may need to put more information/error log here

**Comment by maliho0803** [comment]
nvcr.io/nvidia/pytorch:20.11-py3 

using this docker image, everything is ok!!!
