### ISSUE TITLE
No module named 'basicsr.losses.losses'

### ISSUE THREAD

**Issue by TheodoreXxd** [TencentARC/GFPGAN#213]
thanks for your great work. Here I got some problem when I try to run GFPGAN. I have followed the steps to successfully complete all the requirements, but here comes a ERROR. Please give some help, thank you very much.

➜  GFPGAN git:(master) ✗ python inference_gfpgan.py -i /root/cloud/cephfs-group-internship/light_image_to_image/dataset/xxd_celeba/random_GFPGAN -o results -v 1.3 -s 2
Traceback (most recent call last):
  File "inference_gfpgan.py", line 9, in <module>
    from gfpgan import GFPGANer
  File "/root/picasso/XXD/compareModel/TencentARC_GFPGAN/GFPGAN/gfpgan/__init__.py", line 4, in <module>
    from .models import *
  File "/root/picasso/XXD/compareModel/TencentARC_GFPGAN/GFPGAN/gfpgan/models/__init__.py", line 10, in <module>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "/root/picasso/XXD/compareModel/TencentARC_GFPGAN/GFPGAN/gfpgan/models/__init__.py", line 10, in <listcomp>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/picasso/XXD/compareModel/TencentARC_GFPGAN/GFPGAN/gfpgan/models/gfpgan_model.py", line 6, in <module>
    from basicsr.losses.losses import r1_penalty
ModuleNotFoundError: No module named 'basicsr.losses.losses'

**Comment by towerlina** [comment]
downgrading from 1.4.1 to 1.3.5 works for me

**Comment by TheodoreXxd** [comment]
> downgrading from 1.4.1 to 1.3.5 works for me

thanks， it is works for me ：）

**Comment by pana8888** [comment]
same problem, sorry, which module should be downgrade?

**Comment by elen07zz** [comment]
> same problem, sorry, which module should be downgrade?

basicsr
