### ISSUE TITLE
No module named 'basicsr.losses.gan_loss'

### ISSUE THREAD

**Issue by wsysl1989** [TencentARC/GFPGAN#215]
D:\Python\python.exe N:/python/GFPGAN1.34/GFPGAN-master/inference_gfpgan.py
Traceback (most recent call last):
  File "N:\python\GFPGAN1.34\GFPGAN-master\inference_gfpgan.py", line 9, in <module>
    from gfpgan import GFPGANer
  File "N:\python\GFPGAN1.34\GFPGAN-master\gfpgan\__init__.py", line 4, in <module>
    from .models import *
  File "N:\python\GFPGAN1.34\GFPGAN-master\gfpgan\models\__init__.py", line 10, in <module>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "N:\python\GFPGAN1.34\GFPGAN-master\gfpgan\models\__init__.py", line 10, in <listcomp>
    _model_modules = [importlib.import_module(f'gfpgan.models.{file_name}') for file_name in model_filenames]
  File "D:\Python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "N:\python\GFPGAN1.34\GFPGAN-master\gfpgan\models\gfpgan_model.py", line 6, in <module>
    from basicsr.losses.gan_loss import r1_penalty
ModuleNotFoundError: No module named 'basicsr.losses.gan_loss'

**Comment by tg-bomze** [comment]
```
git clone https://github.com/TencentARC/GFPGAN.git
cd GFPGAN
git checkout bc3f0c4
pip install basicsr==1.3.5
```

**Comment by xinntao** [comment]
update basicsr to the latest version v1.4.0

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by qwe2654** [comment]
Still unsolved.

Installing collected packages: basicsr
  Attempting uninstall: basicsr
    Found existing installation: basicsr 1.3.5
    Uninstalling basicsr-1.3.5:
      Successfully uninstalled basicsr-1.3.5
Successfully installed basicsr-1.4.1

**Comment by Ir1d** [comment]
downgrading from 1.4.1 to 1.3.5 works for me

**Comment by elen07zz** [comment]
change GFPGAN-master\gfpgan\models\gfpgan_model.py

line:  from basicsr.losses.gan_loss import r1_penalty
to
from basicsr.losses.losses import r1_penalty

**Comment by wsysl1989** [comment]
> change GFPGAN-master\gfpgan\models\gfpgan_model.py
> 
> line: from basicsr.losses.gan_loss import r1_penalty to from basicsr.losses.losses import r1_penalty

thanks,but another problem occurs,can not go on again.
Traceback (most recent call last):
  File "N:\python\GFPGAN1.34\GFPGAN-master\inference_gfpgan.py", line 155, in <module>
    main()
  File "N:\python\GFPGAN1.34\GFPGAN-master\inference_gfpgan.py", line 103, in main
    restorer = GFPGANer(
  File "N:\python\GFPGAN1.34\GFPGAN-master\gfpgan\utils.py", line 76, in __init__
    self.face_helper = FaceRestoreHelper(
TypeError: __init__() got an unexpected keyword argument 'use_parse'

**Comment by DZai** [comment]
> TypeError: init() got an unexpected keyword argument 'use_parse'

update basicsr to the version v1.4.2, and update facexlib to 0.2.5 works for me.

**Comment by wsysl1989** [comment]
> > TypeError: init() got an unexpected keyword argument 'use_parse'
> 
> update basicsr to the version v1.4.2, and update facexlib to 0.2.5 works for me. No need to change gfpgan_model.py

thanks，update basicsr to the version v1.4.2, and update facexlib to 0.2.5 ，still change back " from basicsr.losses.gan_loss import r1_penalty".now,it works for me.

**Comment by LightningStalker** [comment]
> change GFPGAN-master\gfpgan\models\gfpgan_model.py
> 
> line: from basicsr.losses.gan_loss import r1_penalty to from basicsr.losses.losses import r1_penalty

This also appears to work in stable-diffusion-krita-plugin though the py script is in a different location.

**Comment by wordsand** [comment]
for my python 3.10.x and basicsr 1.4.2
change to : from basicsr.losses.gan_loss import r1_penalty
works for me.
