### ISSUE TITLE
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by misssunitaparker** [TencentARC/GFPGAN#506]
Traceback (most recent call last):
  File "E:\SOFT\GFPGAN\GFPGAN\inference_gfpgan.py", line 7, in <module>
    from basicsr.utils import imwrite
  File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MKN\anaconda3\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale

**Comment by misssunitaparker** [comment]
![Uploading bdbe9c6d3f2e42f9f79e56e414fe27daed6c1ed0..jpg…]()

**Comment by J-McFc** [comment]
Have you managed to fix it? I'm getting the same when I run the script

**Comment by DNucX** [comment]
@misssunitaparker @J-McFc 

Go to the file degradations.py. It's located in the error message. For example, for @misssunitaparker, it's:

`File "C:\Users\MKN\anaconda3\Lib\site-packages\basicsr\data\degradations.py"`

Open the file degradations.py and edit line 8 from:

`from torchvision.transforms.functional_tensor import rgb_to_grayscale`

to:

`from torchvision.transforms.functional import rgb_to_grayscale`

Hopefully this works.

**Comment by J-McFc** [comment]
@DNucX It works, you're a legend, thanks mate.

**Comment by dinihanafi** [comment]
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[18], [line 3](vscode-notebook-cell:?execution_count=18&line=3)
      [1](vscode-notebook-cell:?execution_count=18&line=1) from pytorchvideo.data import LabeledVideoDataset, Kinetics, make_clip_sampler
----> [3](vscode-notebook-cell:?execution_count=18&line=3) from pytorchvideo.transforms import (ApplyTransformToKey, Normalize, RandomShortSideScale, UniformTemporalSubsample,
      [4](vscode-notebook-cell:?execution_count=18&line=4)                                      )
      [6](vscode-notebook-cell:?execution_count=18&line=6) from torchvision.transforms import (Compose, Lambda, RandomCrop, RandomHorizontalFlip, Resize)
      [8](vscode-notebook-cell:?execution_count=18&line=8) from torchvision.transforms._transforms_video import (CenterCropVideo, NormalizeVideo)

File [c:\Users\pnanurdb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorchvideo\transforms\__init__.py:3](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/__init__.py:3)
      [1](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/__init__.py:1) # Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved.
----> [3](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/__init__.py:3) from .augmix import AugMix  # noqa
      [4](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/__init__.py:4) from .mix import CutMix, MixUp, MixVideo  # noqa
      [5](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/__init__.py:5) from .rand_augment import RandAugment  # noqa

File [c:\Users\pnanurdb\AppData\Local\Programs\Python\Python312\Lib\site-packages\pytorchvideo\transforms\augmix.py:6](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:6)
      [3](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:3) from typing import Any, Dict, Optional
      [5](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:5) import torch
----> [6](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:6) from pytorchvideo.transforms.augmentations import (
      [7](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:7)     _AUGMENTATION_MAX_LEVEL,
      [8](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:8)     AugmentTransform,
      [9](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:9)     _decreasing_int_to_arg,
     [10](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:10)     _decreasing_to_arg,
     [11](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:11)     _increasing_magnitude_to_arg,
     [12](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmix.py:12)     _increasing_randomly_negate_to_arg,
...
----> [9](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmentations.py:9) import torchvision.transforms.functional_tensor as F_t
     [10](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmentations.py:10) from torchvision.transforms.functional import InterpolationMode
     [13](file:///C:/Users/pnanurdb/AppData/Local/Programs/Python/Python312/Lib/site-packages/pytorchvideo/transforms/augmentations.py:13) # Maximum global magnitude used for video augmentation.

ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

Can anyone help me with this error also? Thanks in advanced

**Comment by sunilkumardash9** [comment]
@dinihanafi  change torchvision.transforms.functional_tensor to torchvision.transforms.functional

**Comment by donwany** [comment]
> @DNucX It works, you're a legend, thanks mate.

Mine was 

nano /home/<USERNAME>/miniconda3/envs/gfpgan-demo/lib/python3.12/site-packages/basicsr/data/degradations.py

change line to 

from torchvision.transforms.functional_tensor import rgb_to_grayscale
to:
from torchvision.transforms.functional import rgb_to_grayscale

Then it worked.!

**Comment by Svytta** [comment]
TRY THIS:

import fileinput
import sys

def update_degradations_import(file_path):

> # Original line we want to replace:
    original_line = 'from torchvision.transforms.functional_tensor import rgb_to_grayscale\n'

> # New line that we want to write:
    new_line = 'from torchvision.transforms.functional import rgb_to_grayscale\n'

    

> # Open the file in read and write mode:
    with fileinput.FileInput(file_path, inplace=True, backup='.bak') as file:
        for line in file:
           # Replace the original line with the new line:
            if line == original_line:
                sys.stdout.write(new_line)
            else:
                sys.stdout.write(line)

> # Path to the downgrade file that we want to modify, in my case:

file_path = '/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py'

> # Call function to update import

update_degradations_import(file_path)
print(f"Updated import in {file_path}")

**Comment by yuanjinlong** [comment]
> > @DNucX It works, you're a legend, thanks mate.
> 
> Mine was
> 
> nano /home//miniconda3/envs/gfpgan-demo/lib/python3.12/site-packages/basicsr/data/degradations.py
> 
> change line to
> 
> from torchvision.transforms.functional_tensor import rgb_to_grayscale to: from torchvision.transforms.functional import rgb_to_grayscale
> 
> Then it worked.!

thanks.  the same problem .now it works.
