### ISSUE TITLE
ls: cannot access 'results/cmp': No such file or directory

### ISSUE THREAD

**Issue by shishirahm3d** [TencentARC/GFPGAN#543]
Getting this error on google colab!

Traceback (most recent call last):
  File "/content/GFPGAN/inference_gfpgan.py", line 7, in <module>
    from basicsr.utils import imwrite
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
ls: cannot access 'results/cmp': No such file or directory

**Comment by Mdsaidul566** [comment]
I am coming soon

**Comment by doniaa24** [comment]
@shishirahm3d if you didn't resolve it yet: on the file degradation.py line 8 simply change:
from torchvision.transforms.functional_tensor import rgb_to_grayscale
to:
from torchvision.transforms.functional import rgb_to_grayscale

**Comment by shishirahm3d** [comment]
@doniaa24 it wokred. thank you

**Comment by shishirahm3d** [comment]
@doniaa24 it worked. thank you

**Comment by doniaa24** [comment]
@shishirahm3d did you tried to train the GFPGAN MODEL ?
