### ISSUE TITLE
Windows runs V1 but meets  "time.sleep" problem

### ISSUE THREAD

**Issue by caokx** [TencentARC/GFPGAN#558]
D:\Python\GFPGAN>set BASICSR_JIT=True

D:\Python\GFPGAN>python inference_gfpgan.py -i in_ -o out_ -v 1 -s 2 --ext jpg --bg_upsampler realesrgan --bg_tile 800
Traceback (most recent call last):
  File "D:\Python\GFPGAN\inference_gfpgan.py", line 7, in <module>
    from basicsr.utils import imwrite
  File "D:\Python\Python39\lib\site-packages\basicsr\__init__.py", line 3, in <module>
    from .archs import *
  File "D:\Python\Python39\lib\site-packages\basicsr\archs\__init__.py", line 16, in <module>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Python\Python39\lib\site-packages\basicsr\archs\__init__.py", line 16, in <listcomp>
    _arch_modules = [importlib.import_module(f'basicsr.archs.{file_name}') for file_name in arch_filenames]
  File "D:\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "D:\Python\Python39\lib\site-packages\basicsr\archs\basicvsrpp_arch.py", line 7, in <module>
    from basicsr.archs.arch_util import flow_warp
  File "D:\Python\Python39\lib\site-packages\basicsr\archs\arch_util.py", line 13, in <module>
    from basicsr.ops.dcn import ModulatedDeformConvPack, modulated_deform_conv
  File "D:\Python\Python39\lib\site-packages\basicsr\ops\dcn\__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv, ModulatedDeformConvPack, deform_conv,
  File "D:\Python\Python39\lib\site-packages\basicsr\ops\dcn\deform_conv.py", line 14, in <module>
    deform_conv_ext = load(
  File "D:\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 986, in load
    return _jit_compile(
  File "D:\Python\Python39\lib\site-packages\torch\utils\cpp_extension.py", line 1206, in _jit_compile
    baton.wait()
  File "D:\Python\Python39\lib\site-packages\torch\utils\file_baton.py", line 48, in wait
    time.sleep(self.wait_seconds)
KeyboardInterrupt

**Comment by caokx** [comment]
I have run few hours, but it seems that the code doesn't work
