### ISSUE TITLE
Issue at Step 3: Cannot access 'results/cmp': No such file or directory

### ISSUE THREAD

**Issue by VarunSaiTeja** [TencentARC/GFPGAN#575]
Traceback (most recent call last):
  File "/content/GFPGAN/inference_gfpgan.py", line 7, in <module>
    from basicsr.utils import imwrite
  File "/usr/local/lib/python3.10/dist-packages/basicsr/__init__.py", line 4, in <module>
    from .data import *
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "/usr/local/lib/python3.10/dist-packages/basicsr/data/degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
ls: cannot access 'results/cmp': No such file or directory

**Comment by albtronics** [comment]
**Solution:**
You need to update the file causing the issue, for that open cmd and type: **pip show basicsr**
Note down the location & search for the **degradations.py** file.
Open it & edit the following line:
**_from torchvision.transforms.functional_tensor import rgb_to_grayscale_**
to
from torchvision.transforms.functional import rgb_to_grayscale

**Comment by harryjackson** [comment]
This worked perfectly for me.
