### ISSUE TITLE
No module named 'basicsr'

### ISSUE THREAD

**Issue by lanly-dev** [TencentARC/GFPGAN#592]
Trying to use this with stable diffusion webui, got this error:
```
*** Error loading script: convert_gfpganv_to_clean.py
    Traceback (most recent call last):
      File "C:\Users\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\stable-diffusion-webui\extensions\GFPGAN\scripts\convert_gfpganv_to_clean.py", line 5, in <module>
        from gfpgan.archs.gfpganv1_clean_arch import GFPGANv1Clean
      File "C:\Users\stable-diffusion-webui\extensions\GFPGAN\gfpgan\__init__.py", line 2, in <module>
        from .archs import *
      File "C:\Users\stable-diffusion-webui\extensions\GFPGAN\gfpgan\archs\__init__.py", line 2, in <module>
        from basicsr.utils import scandir
    ModuleNotFoundError: No module named 'basicsr'

---
*** Error loading script: parse_landmark.py
    Traceback (most recent call last):
      File "C:\Users\stable-diffusion-webui\modules\scripts.py", line 515, in load_scripts
        script_module = script_loading.load_module(scriptfile.path)
      File "C:\Users\stable-diffusion-webui\modules\script_loading.py", line 13, in load_module
        module_spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 883, in exec_module
      File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
      File "C:\Users\stable-diffusion-webui\extensions\GFPGAN\scripts\parse_landmark.py", line 6, in <module>
        from basicsr.utils import FileClient, imfrombytes
    ModuleNotFoundError: No module named 'basicsr'
---
```

I'm not sure what to do here, I installed the module, but it doesn't seem to be working :(

**Comment by bcExpt1123** [comment]
No solution yet?
