### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x16384 and 4096x8192)

### ISSUE THREAD

**Issue by zuishuaicaiji** [TencentARC/GFPGAN#80]
请问下作者和大家，训练的时候有碰到这个问题吗，训练的代码一直没有调通，不知道哪里出的问题。期待解答，谢谢。

Traceback (most recent call last):
  File "gfpgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/data/mingyang/tx/BasicSR-master/basicsr/train.py", line 169, in train_pipeline
    model.optimize_parameters(current_iter)
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/gfpgan/models/gfpgan_model.py", line 305, in optimize_parameters
    self.output, out_rgbs = self.net_g(self.lq, return_rgb=True)
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 799, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/gfpgan/archs/gfpganv1_arch.py", line 355, in forward
    style_code = self.final_linear(feat.view(feat.size(0), -1))
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "/data/mingyang/tx/BasicSR-master/basicsr/archs/stylegan2_arch.py", line 174, in forward
    out = F.linear(x, self.weight * self.scale, bias=bias)
  File "/home/mingyang/anaconda3/envs/tx/lib/python3.7/site-packages/torch/nn/functional.py", line 1847, in linear
    return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x16384 and 4096x8192)
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 48829) of binary: /home/mingyang/anaconda3/envs/tx/bin/python

**Comment by alexliyang** [comment]
这个是直接用1024*1024的图像训练了吧，resieze到512*512可以开始训练，但是是否应该resize呢？

**Comment by wangqilongcv** [comment]
> 这个是直接用1024_1024的图像训练了吧，resieze到512_512可以开始训练，但是是否应该resize呢？

请问最后是怎么处理的，resize后是否对最后效果有影响

**Comment by sunjian2015** [comment]
> > 这个是直接用1024_1024的图像训练了吧，resieze到512_512可以开始训练，但是是否应该resize呢？
> 
> 请问最后是怎么处理的，resize后是否对最后效果有影响

请问你是怎么处理的呢？我resize后是可以跑通的。
