### ISSUE TITLE
保存模型出现错误 Save the latest model  calculate_psnr() missing 1 required positional argument: 'img'

### ISSUE THREAD

**Issue by xsmbb** [TencentARC/GFPGAN#99]
我在训练完成 保存模型时出现了一点问题  有没有大哥救救我
2021-11-16 06:22:08,277 INFO: Save the latest model.
  0%|                                                                                                                   | 0/1 [00:00<?, ?image/s]Traceback (most recent call last):
  File "gfpgan/train.py", line 11, in <module>
    train_pipeline(root_path)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/train.py", line 208, in train_pipeline
    model.validation(val_loader, current_iter, tb_logger, opt['val']['save_img'])
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/models/base_model.py", line 46, in validation
    self.dist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/gfpgan/models/gfpgan_model.py", line 483, in dist_validation
    self.nondist_validation(dataloader, current_iter, tb_logger, save_img)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/gfpgan/models/gfpgan_model.py", line 526, in nondist_validation
    self.metric_results[name] += calculate_metric(metric_data, opt_)
  File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/metrics/__init__.py", line 19, in calculate_metric
    metric = METRIC_REGISTRY.get(metric_type)(**data, **opt)

TypeError: calculate_psnr() missing 1 required positional argument: 'img'
  0%|                                                                                                                   | 0/1 [00:00<?, ?image/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 473) of binary: /root/miniconda3/envs/myconda/bin/python

**Comment by chenloveheimei** [comment]
> 我在训练完成 保存模型时出现了一点问题 有没有大哥救救我 2021-11-16 06:22:08,277 INFO: Save the latest model. 0%| | 0/1 [00:00<?, ?image/s]Traceback (most recent call last): File "gfpgan/train.py", line 11, in train_pipeline(root_path) File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/train.py", line 208, in train_pipeline model.validation(val_loader, current_iter, tb_logger, opt['val']['save_img']) File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/models/base_model.py", line 46, in validation self.dist_validation(dataloader, current_iter, tb_logger, save_img) File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/gfpgan/models/gfpgan_model.py", line 483, in dist_validation self.nondist_validation(dataloader, current_iter, tb_logger, save_img) File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/gfpgan/models/gfpgan_model.py", line 526, in nondist_validation self.metric_results[name] += calculate_metric(metric_data, opt_) File "/root/miniconda3/envs/myconda/lib/python3.8/site-packages/basicsr/metrics/**init**.py", line 19, in calculate_metric metric = METRIC_REGISTRY.get(metric_type)(**data, **opt)
> 
> TypeError: calculate_psnr() missing 1 required positional argument: 'img' 0%| | 0/1 [00:00<?, ?image/s] ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 473) of binary: /root/miniconda3/envs/myconda/bin/python

你问题解决了吗？我也遇到这个问题了

**Comment by Zhaiyan1996** [comment]
这两位小哥可以分享一下你们train的过程吗？或者给我指导一下，我现在的问题是这样的：
File "train.py", line 10, in <module>
    train_pipeline(root_path)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/basicsr/train.py", line 169, in train_pipeline
    model.optimize_parameters(current_iter)
  File "/home/yanglin/zhaiyan/GFPGAN/gfpgan/models/gfpgan_model.py", line 308, in optimize_parameters
    self.output, out_rgbs = self.net_g(self.lq, return_rgb=True)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 619, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yanglin/zhaiyan/GFPGAN/gfpgan/archs/gfpganv1_arch.py", line 353, in forward
    feat = self.conv_body_down[i](feat)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/basicsr/archs/stylegan2_arch.py", line 726, in forward
    out = self.conv2(out)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/site-packages/basicsr/archs/stylegan2_arch.py", line 635, in forward
    out = F.conv2d(
TypeError: conv2d(): argument 'input' (position 1) must be Tensor, not NoneType
Traceback (most recent call last):
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/yanglin/anaconda3/envs/zhaiyan3.8/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
盼回复~
